[package]
name = "neo_ws_parser"
version = "0.1.0"
edition = "2021"
authors = ["Andrii Kviatkovskyi"]
description = "A parser for extracting data about near Earth objects."
readme = "README.md"

[dependencies]
anyhow = "1.0.93"
pest = "2.7.14"
pest_derive = "2.7.14"
